// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bootstrapData.proto

package bootstrapStorage

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MiniBlocksInMeta is used to store all mini blocks hashes for a metablock hash
type MiniBlocksInMeta struct {
	MetaHash               []byte   `protobuf:"bytes,1,opt,name=MetaHash,proto3" json:"MetaHash,omitempty"`
	MiniBlocksHashes       [][]byte `protobuf:"bytes,2,rep,name=MiniBlocksHashes,proto3" json:"MiniBlocksHashes,omitempty"`
	FullyProcessed         []bool   `protobuf:"varint,3,rep,packed,name=FullyProcessed,proto3" json:"FullyProcessed,omitempty"`
	IndexOfLastTxProcessed []int32  `protobuf:"varint,4,rep,packed,name=IndexOfLastTxProcessed,proto3" json:"IndexOfLastTxProcessed,omitempty"`
}

func (m *MiniBlocksInMeta) Reset()      { *m = MiniBlocksInMeta{} }
func (*MiniBlocksInMeta) ProtoMessage() {}
func (*MiniBlocksInMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd9e3de0f7706101, []int{0}
}
func (m *MiniBlocksInMeta) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MiniBlocksInMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *MiniBlocksInMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MiniBlocksInMeta.Merge(m, src)
}
func (m *MiniBlocksInMeta) XXX_Size() int {
	return m.Size()
}
func (m *MiniBlocksInMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_MiniBlocksInMeta.DiscardUnknown(m)
}

var xxx_messageInfo_MiniBlocksInMeta proto.InternalMessageInfo

func (m *MiniBlocksInMeta) GetMetaHash() []byte {
	if m != nil {
		return m.MetaHash
	}
	return nil
}

func (m *MiniBlocksInMeta) GetMiniBlocksHashes() [][]byte {
	if m != nil {
		return m.MiniBlocksHashes
	}
	return nil
}

func (m *MiniBlocksInMeta) GetFullyProcessed() []bool {
	if m != nil {
		return m.FullyProcessed
	}
	return nil
}

func (m *MiniBlocksInMeta) GetIndexOfLastTxProcessed() []int32 {
	if m != nil {
		return m.IndexOfLastTxProcessed
	}
	return nil
}

// BootstrapHeaderInfo is used to store information about a header
type BootstrapHeaderInfo struct {
	ShardId uint32 `protobuf:"varint,1,opt,name=ShardId,proto3" json:"ShardId,omitempty"`
	Epoch   uint32 `protobuf:"varint,2,opt,name=Epoch,proto3" json:"Epoch,omitempty"`
	Nonce   uint64 `protobuf:"varint,3,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	Hash    []byte `protobuf:"bytes,4,opt,name=Hash,proto3" json:"Hash,omitempty"`
}

func (m *BootstrapHeaderInfo) Reset()      { *m = BootstrapHeaderInfo{} }
func (*BootstrapHeaderInfo) ProtoMessage() {}
func (*BootstrapHeaderInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd9e3de0f7706101, []int{1}
}
func (m *BootstrapHeaderInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BootstrapHeaderInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *BootstrapHeaderInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BootstrapHeaderInfo.Merge(m, src)
}
func (m *BootstrapHeaderInfo) XXX_Size() int {
	return m.Size()
}
func (m *BootstrapHeaderInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BootstrapHeaderInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BootstrapHeaderInfo proto.InternalMessageInfo

func (m *BootstrapHeaderInfo) GetShardId() uint32 {
	if m != nil {
		return m.ShardId
	}
	return 0
}

func (m *BootstrapHeaderInfo) GetEpoch() uint32 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *BootstrapHeaderInfo) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *BootstrapHeaderInfo) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

// PendingMiniBlocksInfo is used to store information about the number of pending miniblocks
type PendingMiniBlocksInfo struct {
	ShardID          uint32   `protobuf:"varint,1,opt,name=ShardID,proto3" json:"ShardID,omitempty"`
	MiniBlocksHashes [][]byte `protobuf:"bytes,2,rep,name=MiniBlocksHashes,proto3" json:"MiniBlocksHashes,omitempty"`
}

func (m *PendingMiniBlocksInfo) Reset()      { *m = PendingMiniBlocksInfo{} }
func (*PendingMiniBlocksInfo) ProtoMessage() {}
func (*PendingMiniBlocksInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd9e3de0f7706101, []int{2}
}
func (m *PendingMiniBlocksInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PendingMiniBlocksInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *PendingMiniBlocksInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingMiniBlocksInfo.Merge(m, src)
}
func (m *PendingMiniBlocksInfo) XXX_Size() int {
	return m.Size()
}
func (m *PendingMiniBlocksInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingMiniBlocksInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PendingMiniBlocksInfo proto.InternalMessageInfo

func (m *PendingMiniBlocksInfo) GetShardID() uint32 {
	if m != nil {
		return m.ShardID
	}
	return 0
}

func (m *PendingMiniBlocksInfo) GetMiniBlocksHashes() [][]byte {
	if m != nil {
		return m.MiniBlocksHashes
	}
	return nil
}

// BootstrapData is used to store information that are needed for bootstrap
type BootstrapData struct {
	LastHeader                 BootstrapHeaderInfo     `protobuf:"bytes,1,opt,name=LastHeader,proto3" json:"LastHeader"`
	LastCrossNotarizedHeaders  []BootstrapHeaderInfo   `protobuf:"bytes,2,rep,name=LastCrossNotarizedHeaders,proto3" json:"LastCrossNotarizedHeaders"`
	LastSelfNotarizedHeaders   []BootstrapHeaderInfo   `protobuf:"bytes,7,rep,name=LastSelfNotarizedHeaders,proto3" json:"LastSelfNotarizedHeaders"`
	ProcessedMiniBlocks        []MiniBlocksInMeta      `protobuf:"bytes,4,rep,name=ProcessedMiniBlocks,proto3" json:"ProcessedMiniBlocks"`
	PendingMiniBlocks          []PendingMiniBlocksInfo `protobuf:"bytes,8,rep,name=PendingMiniBlocks,proto3" json:"PendingMiniBlocks"`
	NodesCoordinatorConfigKey  []byte                  `protobuf:"bytes,9,opt,name=NodesCoordinatorConfigKey,proto3" json:"NodesCoordinatorConfigKey,omitempty"`
	EpochStartTriggerConfigKey []byte                  `protobuf:"bytes,10,opt,name=EpochStartTriggerConfigKey,proto3" json:"EpochStartTriggerConfigKey,omitempty"`
	HighestFinalBlockNonce     uint64                  `protobuf:"varint,5,opt,name=HighestFinalBlockNonce,proto3" json:"HighestFinalBlockNonce,omitempty"`
	LastRound                  int64                   `protobuf:"varint,6,opt,name=LastRound,proto3" json:"LastRound,omitempty"`
	OutGoingNonces             map[string]uint64       `protobuf:"bytes,20,rep,name=OutGoingNonces,proto3" json:"OutGoingNonces,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (m *BootstrapData) Reset()      { *m = BootstrapData{} }
func (*BootstrapData) ProtoMessage() {}
func (*BootstrapData) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd9e3de0f7706101, []int{3}
}
func (m *BootstrapData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BootstrapData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *BootstrapData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BootstrapData.Merge(m, src)
}
func (m *BootstrapData) XXX_Size() int {
	return m.Size()
}
func (m *BootstrapData) XXX_DiscardUnknown() {
	xxx_messageInfo_BootstrapData.DiscardUnknown(m)
}

var xxx_messageInfo_BootstrapData proto.InternalMessageInfo

func (m *BootstrapData) GetLastHeader() BootstrapHeaderInfo {
	if m != nil {
		return m.LastHeader
	}
	return BootstrapHeaderInfo{}
}

func (m *BootstrapData) GetLastCrossNotarizedHeaders() []BootstrapHeaderInfo {
	if m != nil {
		return m.LastCrossNotarizedHeaders
	}
	return nil
}

func (m *BootstrapData) GetLastSelfNotarizedHeaders() []BootstrapHeaderInfo {
	if m != nil {
		return m.LastSelfNotarizedHeaders
	}
	return nil
}

func (m *BootstrapData) GetProcessedMiniBlocks() []MiniBlocksInMeta {
	if m != nil {
		return m.ProcessedMiniBlocks
	}
	return nil
}

func (m *BootstrapData) GetPendingMiniBlocks() []PendingMiniBlocksInfo {
	if m != nil {
		return m.PendingMiniBlocks
	}
	return nil
}

func (m *BootstrapData) GetNodesCoordinatorConfigKey() []byte {
	if m != nil {
		return m.NodesCoordinatorConfigKey
	}
	return nil
}

func (m *BootstrapData) GetEpochStartTriggerConfigKey() []byte {
	if m != nil {
		return m.EpochStartTriggerConfigKey
	}
	return nil
}

func (m *BootstrapData) GetHighestFinalBlockNonce() uint64 {
	if m != nil {
		return m.HighestFinalBlockNonce
	}
	return 0
}

func (m *BootstrapData) GetLastRound() int64 {
	if m != nil {
		return m.LastRound
	}
	return 0
}

func (m *BootstrapData) GetOutGoingNonces() map[string]uint64 {
	if m != nil {
		return m.OutGoingNonces
	}
	return nil
}

type RoundNum struct {
	Num int64 `protobuf:"varint,1,opt,name=Num,proto3" json:"Num,omitempty"`
}

func (m *RoundNum) Reset()      { *m = RoundNum{} }
func (*RoundNum) ProtoMessage() {}
func (*RoundNum) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd9e3de0f7706101, []int{4}
}
func (m *RoundNum) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RoundNum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *RoundNum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoundNum.Merge(m, src)
}
func (m *RoundNum) XXX_Size() int {
	return m.Size()
}
func (m *RoundNum) XXX_DiscardUnknown() {
	xxx_messageInfo_RoundNum.DiscardUnknown(m)
}

var xxx_messageInfo_RoundNum proto.InternalMessageInfo

func (m *RoundNum) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

func init() {
	proto.RegisterType((*MiniBlocksInMeta)(nil), "proto.MiniBlocksInMeta")
	proto.RegisterType((*BootstrapHeaderInfo)(nil), "proto.BootstrapHeaderInfo")
	proto.RegisterType((*PendingMiniBlocksInfo)(nil), "proto.PendingMiniBlocksInfo")
	proto.RegisterType((*BootstrapData)(nil), "proto.BootstrapData")
	proto.RegisterMapType((map[string]uint64)(nil), "proto.BootstrapData.OutGoingNoncesEntry")
	proto.RegisterType((*RoundNum)(nil), "proto.RoundNum")
}

func init() { proto.RegisterFile("bootstrapData.proto", fileDescriptor_cd9e3de0f7706101) }

var fileDescriptor_cd9e3de0f7706101 = []byte{
	// 656 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x6e, 0x13, 0x3d,
	0x14, 0x1d, 0x77, 0x92, 0x36, 0x75, 0x7f, 0xd4, 0xcf, 0xe9, 0x07, 0xd3, 0xa8, 0x32, 0x51, 0x16,
	0x68, 0x84, 0x44, 0x2b, 0x15, 0x09, 0x21, 0x84, 0x10, 0xa4, 0x3f, 0x34, 0x40, 0xd3, 0xc8, 0xe9,
	0x0a, 0x01, 0x92, 0x93, 0x71, 0x26, 0xa3, 0xa6, 0x76, 0xe5, 0xf1, 0xa0, 0x86, 0x15, 0x8f, 0xc0,
	0x9e, 0x17, 0xe0, 0x19, 0x78, 0x82, 0x2e, 0xbb, 0xec, 0x0a, 0xd1, 0xe9, 0x86, 0x65, 0x1f, 0x01,
	0xcd, 0x9d, 0xb4, 0x4d, 0xf3, 0x83, 0xca, 0x6a, 0x7c, 0xae, 0xef, 0x39, 0xe3, 0x7b, 0xee, 0xb5,
	0x71, 0xbe, 0xa1, 0x94, 0x09, 0x8d, 0xe6, 0x87, 0x1b, 0xdc, 0xf0, 0x95, 0x43, 0xad, 0x8c, 0x22,
	0x59, 0xf8, 0x14, 0x1e, 0xfa, 0x81, 0x69, 0x47, 0x8d, 0x95, 0xa6, 0x3a, 0x58, 0xf5, 0x95, 0xaf,
	0x56, 0x21, 0xdc, 0x88, 0x5a, 0x80, 0x00, 0xc0, 0x2a, 0x65, 0x95, 0x7e, 0x20, 0xbc, 0xb0, 0x13,
	0xc8, 0xa0, 0xdc, 0x51, 0xcd, 0xfd, 0xb0, 0x22, 0x77, 0x84, 0xe1, 0xa4, 0x80, 0x73, 0xc9, 0x77,
	0x9b, 0x87, 0x6d, 0x07, 0x15, 0x91, 0x3b, 0xcb, 0xae, 0x30, 0x79, 0xd0, 0x9f, 0x9f, 0x44, 0x44,
	0xe8, 0x4c, 0x14, 0x6d, 0x77, 0x96, 0x0d, 0xc5, 0xc9, 0x7d, 0x3c, 0xbf, 0x15, 0x75, 0x3a, 0xdd,
	0x9a, 0x56, 0x4d, 0x11, 0x86, 0xc2, 0x73, 0xec, 0xa2, 0xed, 0xe6, 0xd8, 0x40, 0x94, 0x3c, 0xc6,
	0x77, 0x2a, 0xd2, 0x13, 0x47, 0xbb, 0xad, 0xb7, 0x3c, 0x34, 0x7b, 0x47, 0xd7, 0xf9, 0x99, 0xa2,
	0xed, 0x66, 0xd9, 0x98, 0xdd, 0x92, 0xc2, 0xf9, 0xf2, 0xa5, 0x13, 0xdb, 0x82, 0x7b, 0x42, 0x57,
	0x64, 0x4b, 0x11, 0x07, 0x4f, 0xd5, 0xdb, 0x5c, 0x7b, 0x15, 0x0f, 0x4e, 0x3f, 0xc7, 0x2e, 0x21,
	0x59, 0xc4, 0xd9, 0xcd, 0x43, 0xd5, 0x6c, 0x3b, 0x13, 0x10, 0x4f, 0x41, 0x12, 0xad, 0x2a, 0xd9,
	0x14, 0x8e, 0x5d, 0x44, 0x6e, 0x86, 0xa5, 0x80, 0x10, 0x9c, 0x01, 0x03, 0x32, 0x60, 0x00, 0xac,
	0x4b, 0x1f, 0xf0, 0xff, 0x35, 0x21, 0xbd, 0x40, 0xfa, 0xfd, 0x9e, 0xf5, 0xff, 0x72, 0xe3, 0xe6,
	0x2f, 0x37, 0xfe, 0xc5, 0xaf, 0xd2, 0xb7, 0x49, 0x3c, 0x57, 0xee, 0x6f, 0x2d, 0x79, 0x81, 0x71,
	0x52, 0x74, 0x5a, 0x1c, 0x48, 0xcf, 0xac, 0x15, 0xd2, 0xd6, 0xad, 0x8c, 0x28, 0xbd, 0x9c, 0x39,
	0xfe, 0x79, 0xcf, 0x62, 0x7d, 0x1c, 0xf2, 0x11, 0x2f, 0x25, 0x68, 0x5d, 0xab, 0x30, 0xac, 0x2a,
	0xc3, 0x75, 0xf0, 0x59, 0x78, 0xe9, 0x5e, 0x7a, 0x90, 0xdb, 0x08, 0x8e, 0x97, 0x20, 0xef, 0xb1,
	0x93, 0x6c, 0xd6, 0x45, 0xa7, 0x35, 0x24, 0x3f, 0x75, 0x4b, 0xf9, 0xb1, 0x0a, 0x64, 0x17, 0xe7,
	0xaf, 0xda, 0x7d, 0x6d, 0x17, 0x8c, 0xc5, 0xcc, 0xda, 0xdd, 0x9e, 0xf0, 0xe0, 0xfc, 0xf6, 0x54,
	0x47, 0x31, 0x49, 0x0d, 0xff, 0x37, 0xd4, 0x41, 0x27, 0x07, 0x72, 0xcb, 0x3d, 0xb9, 0x91, 0x1d,
	0xee, 0x69, 0x0e, 0x93, 0xc9, 0x33, 0xbc, 0x54, 0x55, 0x9e, 0x08, 0xd7, 0x95, 0xd2, 0x5e, 0x20,
	0xb9, 0x51, 0x7a, 0x5d, 0xc9, 0x56, 0xe0, 0xbf, 0x11, 0x5d, 0x67, 0x1a, 0x86, 0x67, 0x7c, 0x02,
	0x79, 0x8e, 0x0b, 0x30, 0x84, 0x75, 0xc3, 0xb5, 0xd9, 0xd3, 0x81, 0xef, 0x8b, 0x3e, 0x3a, 0x06,
	0xfa, 0x5f, 0x32, 0x92, 0xab, 0xb3, 0x1d, 0xf8, 0x6d, 0x11, 0x9a, 0xad, 0x40, 0xf2, 0x0e, 0x9c,
	0x29, 0x1d, 0xe6, 0x2c, 0x0c, 0xf3, 0x98, 0x5d, 0xb2, 0x8c, 0xa7, 0x13, 0xd3, 0x99, 0x8a, 0xa4,
	0xe7, 0x4c, 0x16, 0x91, 0x6b, 0xb3, 0xeb, 0x00, 0xa9, 0xe1, 0xf9, 0xdd, 0xc8, 0xbc, 0x52, 0x81,
	0xf4, 0x21, 0x3d, 0x74, 0x16, 0xc1, 0x22, 0x77, 0xb0, 0x95, 0xf0, 0xfe, 0xdc, 0x4c, 0xdd, 0x94,
	0x46, 0x77, 0xd9, 0x00, 0xbf, 0xf0, 0x12, 0xe7, 0x47, 0xa4, 0x91, 0x05, 0x6c, 0xef, 0x8b, 0x2e,
	0x0c, 0xf6, 0x34, 0x4b, 0x96, 0xc9, 0x65, 0xfc, 0xc4, 0x3b, 0x91, 0x80, 0x2b, 0x9a, 0x61, 0x29,
	0x78, 0x3a, 0xf1, 0x04, 0x95, 0x96, 0x71, 0x0e, 0x4e, 0x57, 0x8d, 0x0e, 0x12, 0x5e, 0x35, 0x3a,
	0x00, 0x9e, 0xcd, 0x92, 0x65, 0xf9, 0xf5, 0xc9, 0x19, 0xb5, 0x4e, 0xcf, 0xa8, 0x75, 0x71, 0x46,
	0xd1, 0x97, 0x98, 0xa2, 0xef, 0x31, 0x45, 0xc7, 0x31, 0x45, 0x27, 0x31, 0x45, 0xa7, 0x31, 0x45,
	0xbf, 0x62, 0x8a, 0x7e, 0xc7, 0xd4, 0xba, 0x88, 0x29, 0xfa, 0x7a, 0x4e, 0xad, 0x93, 0x73, 0x6a,
	0x9d, 0x9e, 0x53, 0xeb, 0xdd, 0xc2, 0xd5, 0x6b, 0x5a, 0x37, 0x4a, 0x73, 0x5f, 0x34, 0x26, 0xa1,
	0xca, 0x47, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xf0, 0xfa, 0x69, 0x87, 0x68, 0x05, 0x00, 0x00,
}

func (this *MiniBlocksInMeta) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MiniBlocksInMeta)
	if !ok {
		that2, ok := that.(MiniBlocksInMeta)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.MetaHash, that1.MetaHash) {
		return false
	}
	if len(this.MiniBlocksHashes) != len(that1.MiniBlocksHashes) {
		return false
	}
	for i := range this.MiniBlocksHashes {
		if !bytes.Equal(this.MiniBlocksHashes[i], that1.MiniBlocksHashes[i]) {
			return false
		}
	}
	if len(this.FullyProcessed) != len(that1.FullyProcessed) {
		return false
	}
	for i := range this.FullyProcessed {
		if this.FullyProcessed[i] != that1.FullyProcessed[i] {
			return false
		}
	}
	if len(this.IndexOfLastTxProcessed) != len(that1.IndexOfLastTxProcessed) {
		return false
	}
	for i := range this.IndexOfLastTxProcessed {
		if this.IndexOfLastTxProcessed[i] != that1.IndexOfLastTxProcessed[i] {
			return false
		}
	}
	return true
}
func (this *BootstrapHeaderInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*BootstrapHeaderInfo)
	if !ok {
		that2, ok := that.(BootstrapHeaderInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ShardId != that1.ShardId {
		return false
	}
	if this.Epoch != that1.Epoch {
		return false
	}
	if this.Nonce != that1.Nonce {
		return false
	}
	if !bytes.Equal(this.Hash, that1.Hash) {
		return false
	}
	return true
}
func (this *PendingMiniBlocksInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PendingMiniBlocksInfo)
	if !ok {
		that2, ok := that.(PendingMiniBlocksInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ShardID != that1.ShardID {
		return false
	}
	if len(this.MiniBlocksHashes) != len(that1.MiniBlocksHashes) {
		return false
	}
	for i := range this.MiniBlocksHashes {
		if !bytes.Equal(this.MiniBlocksHashes[i], that1.MiniBlocksHashes[i]) {
			return false
		}
	}
	return true
}
func (this *BootstrapData) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*BootstrapData)
	if !ok {
		that2, ok := that.(BootstrapData)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.LastHeader.Equal(&that1.LastHeader) {
		return false
	}
	if len(this.LastCrossNotarizedHeaders) != len(that1.LastCrossNotarizedHeaders) {
		return false
	}
	for i := range this.LastCrossNotarizedHeaders {
		if !this.LastCrossNotarizedHeaders[i].Equal(&that1.LastCrossNotarizedHeaders[i]) {
			return false
		}
	}
	if len(this.LastSelfNotarizedHeaders) != len(that1.LastSelfNotarizedHeaders) {
		return false
	}
	for i := range this.LastSelfNotarizedHeaders {
		if !this.LastSelfNotarizedHeaders[i].Equal(&that1.LastSelfNotarizedHeaders[i]) {
			return false
		}
	}
	if len(this.ProcessedMiniBlocks) != len(that1.ProcessedMiniBlocks) {
		return false
	}
	for i := range this.ProcessedMiniBlocks {
		if !this.ProcessedMiniBlocks[i].Equal(&that1.ProcessedMiniBlocks[i]) {
			return false
		}
	}
	if len(this.PendingMiniBlocks) != len(that1.PendingMiniBlocks) {
		return false
	}
	for i := range this.PendingMiniBlocks {
		if !this.PendingMiniBlocks[i].Equal(&that1.PendingMiniBlocks[i]) {
			return false
		}
	}
	if !bytes.Equal(this.NodesCoordinatorConfigKey, that1.NodesCoordinatorConfigKey) {
		return false
	}
	if !bytes.Equal(this.EpochStartTriggerConfigKey, that1.EpochStartTriggerConfigKey) {
		return false
	}
	if this.HighestFinalBlockNonce != that1.HighestFinalBlockNonce {
		return false
	}
	if this.LastRound != that1.LastRound {
		return false
	}
	if len(this.OutGoingNonces) != len(that1.OutGoingNonces) {
		return false
	}
	for i := range this.OutGoingNonces {
		if this.OutGoingNonces[i] != that1.OutGoingNonces[i] {
			return false
		}
	}
	return true
}
func (this *RoundNum) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RoundNum)
	if !ok {
		that2, ok := that.(RoundNum)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Num != that1.Num {
		return false
	}
	return true
}
func (this *MiniBlocksInMeta) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&bootstrapStorage.MiniBlocksInMeta{")
	s = append(s, "MetaHash: "+fmt.Sprintf("%#v", this.MetaHash)+",\n")
	s = append(s, "MiniBlocksHashes: "+fmt.Sprintf("%#v", this.MiniBlocksHashes)+",\n")
	s = append(s, "FullyProcessed: "+fmt.Sprintf("%#v", this.FullyProcessed)+",\n")
	s = append(s, "IndexOfLastTxProcessed: "+fmt.Sprintf("%#v", this.IndexOfLastTxProcessed)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *BootstrapHeaderInfo) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&bootstrapStorage.BootstrapHeaderInfo{")
	s = append(s, "ShardId: "+fmt.Sprintf("%#v", this.ShardId)+",\n")
	s = append(s, "Epoch: "+fmt.Sprintf("%#v", this.Epoch)+",\n")
	s = append(s, "Nonce: "+fmt.Sprintf("%#v", this.Nonce)+",\n")
	s = append(s, "Hash: "+fmt.Sprintf("%#v", this.Hash)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *PendingMiniBlocksInfo) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&bootstrapStorage.PendingMiniBlocksInfo{")
	s = append(s, "ShardID: "+fmt.Sprintf("%#v", this.ShardID)+",\n")
	s = append(s, "MiniBlocksHashes: "+fmt.Sprintf("%#v", this.MiniBlocksHashes)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *BootstrapData) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 14)
	s = append(s, "&bootstrapStorage.BootstrapData{")
	s = append(s, "LastHeader: "+strings.Replace(this.LastHeader.GoString(), `&`, ``, 1)+",\n")
	if this.LastCrossNotarizedHeaders != nil {
		vs := make([]BootstrapHeaderInfo, len(this.LastCrossNotarizedHeaders))
		for i := range vs {
			vs[i] = this.LastCrossNotarizedHeaders[i]
		}
		s = append(s, "LastCrossNotarizedHeaders: "+fmt.Sprintf("%#v", vs)+",\n")
	}
	if this.LastSelfNotarizedHeaders != nil {
		vs := make([]BootstrapHeaderInfo, len(this.LastSelfNotarizedHeaders))
		for i := range vs {
			vs[i] = this.LastSelfNotarizedHeaders[i]
		}
		s = append(s, "LastSelfNotarizedHeaders: "+fmt.Sprintf("%#v", vs)+",\n")
	}
	if this.ProcessedMiniBlocks != nil {
		vs := make([]MiniBlocksInMeta, len(this.ProcessedMiniBlocks))
		for i := range vs {
			vs[i] = this.ProcessedMiniBlocks[i]
		}
		s = append(s, "ProcessedMiniBlocks: "+fmt.Sprintf("%#v", vs)+",\n")
	}
	if this.PendingMiniBlocks != nil {
		vs := make([]PendingMiniBlocksInfo, len(this.PendingMiniBlocks))
		for i := range vs {
			vs[i] = this.PendingMiniBlocks[i]
		}
		s = append(s, "PendingMiniBlocks: "+fmt.Sprintf("%#v", vs)+",\n")
	}
	s = append(s, "NodesCoordinatorConfigKey: "+fmt.Sprintf("%#v", this.NodesCoordinatorConfigKey)+",\n")
	s = append(s, "EpochStartTriggerConfigKey: "+fmt.Sprintf("%#v", this.EpochStartTriggerConfigKey)+",\n")
	s = append(s, "HighestFinalBlockNonce: "+fmt.Sprintf("%#v", this.HighestFinalBlockNonce)+",\n")
	s = append(s, "LastRound: "+fmt.Sprintf("%#v", this.LastRound)+",\n")
	keysForOutGoingNonces := make([]string, 0, len(this.OutGoingNonces))
	for k, _ := range this.OutGoingNonces {
		keysForOutGoingNonces = append(keysForOutGoingNonces, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForOutGoingNonces)
	mapStringForOutGoingNonces := "map[string]uint64{"
	for _, k := range keysForOutGoingNonces {
		mapStringForOutGoingNonces += fmt.Sprintf("%#v: %#v,", k, this.OutGoingNonces[k])
	}
	mapStringForOutGoingNonces += "}"
	if this.OutGoingNonces != nil {
		s = append(s, "OutGoingNonces: "+mapStringForOutGoingNonces+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *RoundNum) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&bootstrapStorage.RoundNum{")
	s = append(s, "Num: "+fmt.Sprintf("%#v", this.Num)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringBootstrapData(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *MiniBlocksInMeta) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MiniBlocksInMeta) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MiniBlocksInMeta) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.IndexOfLastTxProcessed) > 0 {
		dAtA2 := make([]byte, len(m.IndexOfLastTxProcessed)*10)
		var j1 int
		for _, num1 := range m.IndexOfLastTxProcessed {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintBootstrapData(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x22
	}
	if len(m.FullyProcessed) > 0 {
		for iNdEx := len(m.FullyProcessed) - 1; iNdEx >= 0; iNdEx-- {
			i--
			if m.FullyProcessed[iNdEx] {
				dAtA[i] = 1
			} else {
				dAtA[i] = 0
			}
		}
		i = encodeVarintBootstrapData(dAtA, i, uint64(len(m.FullyProcessed)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.MiniBlocksHashes) > 0 {
		for iNdEx := len(m.MiniBlocksHashes) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.MiniBlocksHashes[iNdEx])
			copy(dAtA[i:], m.MiniBlocksHashes[iNdEx])
			i = encodeVarintBootstrapData(dAtA, i, uint64(len(m.MiniBlocksHashes[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.MetaHash) > 0 {
		i -= len(m.MetaHash)
		copy(dAtA[i:], m.MetaHash)
		i = encodeVarintBootstrapData(dAtA, i, uint64(len(m.MetaHash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *BootstrapHeaderInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BootstrapHeaderInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BootstrapHeaderInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintBootstrapData(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0x22
	}
	if m.Nonce != 0 {
		i = encodeVarintBootstrapData(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x18
	}
	if m.Epoch != 0 {
		i = encodeVarintBootstrapData(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x10
	}
	if m.ShardId != 0 {
		i = encodeVarintBootstrapData(dAtA, i, uint64(m.ShardId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *PendingMiniBlocksInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PendingMiniBlocksInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PendingMiniBlocksInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MiniBlocksHashes) > 0 {
		for iNdEx := len(m.MiniBlocksHashes) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.MiniBlocksHashes[iNdEx])
			copy(dAtA[i:], m.MiniBlocksHashes[iNdEx])
			i = encodeVarintBootstrapData(dAtA, i, uint64(len(m.MiniBlocksHashes[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if m.ShardID != 0 {
		i = encodeVarintBootstrapData(dAtA, i, uint64(m.ShardID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *BootstrapData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BootstrapData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BootstrapData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OutGoingNonces) > 0 {
		keysForOutGoingNonces := make([]string, 0, len(m.OutGoingNonces))
		for k := range m.OutGoingNonces {
			keysForOutGoingNonces = append(keysForOutGoingNonces, string(k))
		}
		github_com_gogo_protobuf_sortkeys.Strings(keysForOutGoingNonces)
		for iNdEx := len(keysForOutGoingNonces) - 1; iNdEx >= 0; iNdEx-- {
			v := m.OutGoingNonces[string(keysForOutGoingNonces[iNdEx])]
			baseI := i
			i = encodeVarintBootstrapData(dAtA, i, uint64(v))
			i--
			dAtA[i] = 0x10
			i -= len(keysForOutGoingNonces[iNdEx])
			copy(dAtA[i:], keysForOutGoingNonces[iNdEx])
			i = encodeVarintBootstrapData(dAtA, i, uint64(len(keysForOutGoingNonces[iNdEx])))
			i--
			dAtA[i] = 0xa
			i = encodeVarintBootstrapData(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0xa2
		}
	}
	if len(m.EpochStartTriggerConfigKey) > 0 {
		i -= len(m.EpochStartTriggerConfigKey)
		copy(dAtA[i:], m.EpochStartTriggerConfigKey)
		i = encodeVarintBootstrapData(dAtA, i, uint64(len(m.EpochStartTriggerConfigKey)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.NodesCoordinatorConfigKey) > 0 {
		i -= len(m.NodesCoordinatorConfigKey)
		copy(dAtA[i:], m.NodesCoordinatorConfigKey)
		i = encodeVarintBootstrapData(dAtA, i, uint64(len(m.NodesCoordinatorConfigKey)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.PendingMiniBlocks) > 0 {
		for iNdEx := len(m.PendingMiniBlocks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PendingMiniBlocks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintBootstrapData(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.LastSelfNotarizedHeaders) > 0 {
		for iNdEx := len(m.LastSelfNotarizedHeaders) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.LastSelfNotarizedHeaders[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintBootstrapData(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if m.LastRound != 0 {
		i = encodeVarintBootstrapData(dAtA, i, uint64(m.LastRound))
		i--
		dAtA[i] = 0x30
	}
	if m.HighestFinalBlockNonce != 0 {
		i = encodeVarintBootstrapData(dAtA, i, uint64(m.HighestFinalBlockNonce))
		i--
		dAtA[i] = 0x28
	}
	if len(m.ProcessedMiniBlocks) > 0 {
		for iNdEx := len(m.ProcessedMiniBlocks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ProcessedMiniBlocks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintBootstrapData(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.LastCrossNotarizedHeaders) > 0 {
		for iNdEx := len(m.LastCrossNotarizedHeaders) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.LastCrossNotarizedHeaders[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintBootstrapData(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.LastHeader.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintBootstrapData(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *RoundNum) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RoundNum) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RoundNum) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Num != 0 {
		i = encodeVarintBootstrapData(dAtA, i, uint64(m.Num))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintBootstrapData(dAtA []byte, offset int, v uint64) int {
	offset -= sovBootstrapData(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MiniBlocksInMeta) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MetaHash)
	if l > 0 {
		n += 1 + l + sovBootstrapData(uint64(l))
	}
	if len(m.MiniBlocksHashes) > 0 {
		for _, b := range m.MiniBlocksHashes {
			l = len(b)
			n += 1 + l + sovBootstrapData(uint64(l))
		}
	}
	if len(m.FullyProcessed) > 0 {
		n += 1 + sovBootstrapData(uint64(len(m.FullyProcessed))) + len(m.FullyProcessed)*1
	}
	if len(m.IndexOfLastTxProcessed) > 0 {
		l = 0
		for _, e := range m.IndexOfLastTxProcessed {
			l += sovBootstrapData(uint64(e))
		}
		n += 1 + sovBootstrapData(uint64(l)) + l
	}
	return n
}

func (m *BootstrapHeaderInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ShardId != 0 {
		n += 1 + sovBootstrapData(uint64(m.ShardId))
	}
	if m.Epoch != 0 {
		n += 1 + sovBootstrapData(uint64(m.Epoch))
	}
	if m.Nonce != 0 {
		n += 1 + sovBootstrapData(uint64(m.Nonce))
	}
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovBootstrapData(uint64(l))
	}
	return n
}

func (m *PendingMiniBlocksInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ShardID != 0 {
		n += 1 + sovBootstrapData(uint64(m.ShardID))
	}
	if len(m.MiniBlocksHashes) > 0 {
		for _, b := range m.MiniBlocksHashes {
			l = len(b)
			n += 1 + l + sovBootstrapData(uint64(l))
		}
	}
	return n
}

func (m *BootstrapData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.LastHeader.Size()
	n += 1 + l + sovBootstrapData(uint64(l))
	if len(m.LastCrossNotarizedHeaders) > 0 {
		for _, e := range m.LastCrossNotarizedHeaders {
			l = e.Size()
			n += 1 + l + sovBootstrapData(uint64(l))
		}
	}
	if len(m.ProcessedMiniBlocks) > 0 {
		for _, e := range m.ProcessedMiniBlocks {
			l = e.Size()
			n += 1 + l + sovBootstrapData(uint64(l))
		}
	}
	if m.HighestFinalBlockNonce != 0 {
		n += 1 + sovBootstrapData(uint64(m.HighestFinalBlockNonce))
	}
	if m.LastRound != 0 {
		n += 1 + sovBootstrapData(uint64(m.LastRound))
	}
	if len(m.LastSelfNotarizedHeaders) > 0 {
		for _, e := range m.LastSelfNotarizedHeaders {
			l = e.Size()
			n += 1 + l + sovBootstrapData(uint64(l))
		}
	}
	if len(m.PendingMiniBlocks) > 0 {
		for _, e := range m.PendingMiniBlocks {
			l = e.Size()
			n += 1 + l + sovBootstrapData(uint64(l))
		}
	}
	l = len(m.NodesCoordinatorConfigKey)
	if l > 0 {
		n += 1 + l + sovBootstrapData(uint64(l))
	}
	l = len(m.EpochStartTriggerConfigKey)
	if l > 0 {
		n += 1 + l + sovBootstrapData(uint64(l))
	}
	if len(m.OutGoingNonces) > 0 {
		for k, v := range m.OutGoingNonces {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovBootstrapData(uint64(len(k))) + 1 + sovBootstrapData(uint64(v))
			n += mapEntrySize + 2 + sovBootstrapData(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *RoundNum) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Num != 0 {
		n += 1 + sovBootstrapData(uint64(m.Num))
	}
	return n
}

func sovBootstrapData(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBootstrapData(x uint64) (n int) {
	return sovBootstrapData(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *MiniBlocksInMeta) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&MiniBlocksInMeta{`,
		`MetaHash:` + fmt.Sprintf("%v", this.MetaHash) + `,`,
		`MiniBlocksHashes:` + fmt.Sprintf("%v", this.MiniBlocksHashes) + `,`,
		`FullyProcessed:` + fmt.Sprintf("%v", this.FullyProcessed) + `,`,
		`IndexOfLastTxProcessed:` + fmt.Sprintf("%v", this.IndexOfLastTxProcessed) + `,`,
		`}`,
	}, "")
	return s
}
func (this *BootstrapHeaderInfo) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&BootstrapHeaderInfo{`,
		`ShardId:` + fmt.Sprintf("%v", this.ShardId) + `,`,
		`Epoch:` + fmt.Sprintf("%v", this.Epoch) + `,`,
		`Nonce:` + fmt.Sprintf("%v", this.Nonce) + `,`,
		`Hash:` + fmt.Sprintf("%v", this.Hash) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PendingMiniBlocksInfo) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PendingMiniBlocksInfo{`,
		`ShardID:` + fmt.Sprintf("%v", this.ShardID) + `,`,
		`MiniBlocksHashes:` + fmt.Sprintf("%v", this.MiniBlocksHashes) + `,`,
		`}`,
	}, "")
	return s
}
func (this *BootstrapData) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForLastCrossNotarizedHeaders := "[]BootstrapHeaderInfo{"
	for _, f := range this.LastCrossNotarizedHeaders {
		repeatedStringForLastCrossNotarizedHeaders += strings.Replace(strings.Replace(f.String(), "BootstrapHeaderInfo", "BootstrapHeaderInfo", 1), `&`, ``, 1) + ","
	}
	repeatedStringForLastCrossNotarizedHeaders += "}"
	repeatedStringForProcessedMiniBlocks := "[]MiniBlocksInMeta{"
	for _, f := range this.ProcessedMiniBlocks {
		repeatedStringForProcessedMiniBlocks += strings.Replace(strings.Replace(f.String(), "MiniBlocksInMeta", "MiniBlocksInMeta", 1), `&`, ``, 1) + ","
	}
	repeatedStringForProcessedMiniBlocks += "}"
	repeatedStringForLastSelfNotarizedHeaders := "[]BootstrapHeaderInfo{"
	for _, f := range this.LastSelfNotarizedHeaders {
		repeatedStringForLastSelfNotarizedHeaders += strings.Replace(strings.Replace(f.String(), "BootstrapHeaderInfo", "BootstrapHeaderInfo", 1), `&`, ``, 1) + ","
	}
	repeatedStringForLastSelfNotarizedHeaders += "}"
	repeatedStringForPendingMiniBlocks := "[]PendingMiniBlocksInfo{"
	for _, f := range this.PendingMiniBlocks {
		repeatedStringForPendingMiniBlocks += strings.Replace(strings.Replace(f.String(), "PendingMiniBlocksInfo", "PendingMiniBlocksInfo", 1), `&`, ``, 1) + ","
	}
	repeatedStringForPendingMiniBlocks += "}"
	keysForOutGoingNonces := make([]string, 0, len(this.OutGoingNonces))
	for k, _ := range this.OutGoingNonces {
		keysForOutGoingNonces = append(keysForOutGoingNonces, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForOutGoingNonces)
	mapStringForOutGoingNonces := "map[string]uint64{"
	for _, k := range keysForOutGoingNonces {
		mapStringForOutGoingNonces += fmt.Sprintf("%v: %v,", k, this.OutGoingNonces[k])
	}
	mapStringForOutGoingNonces += "}"
	s := strings.Join([]string{`&BootstrapData{`,
		`LastHeader:` + strings.Replace(strings.Replace(this.LastHeader.String(), "BootstrapHeaderInfo", "BootstrapHeaderInfo", 1), `&`, ``, 1) + `,`,
		`LastCrossNotarizedHeaders:` + repeatedStringForLastCrossNotarizedHeaders + `,`,
		`ProcessedMiniBlocks:` + repeatedStringForProcessedMiniBlocks + `,`,
		`HighestFinalBlockNonce:` + fmt.Sprintf("%v", this.HighestFinalBlockNonce) + `,`,
		`LastRound:` + fmt.Sprintf("%v", this.LastRound) + `,`,
		`LastSelfNotarizedHeaders:` + repeatedStringForLastSelfNotarizedHeaders + `,`,
		`PendingMiniBlocks:` + repeatedStringForPendingMiniBlocks + `,`,
		`NodesCoordinatorConfigKey:` + fmt.Sprintf("%v", this.NodesCoordinatorConfigKey) + `,`,
		`EpochStartTriggerConfigKey:` + fmt.Sprintf("%v", this.EpochStartTriggerConfigKey) + `,`,
		`OutGoingNonces:` + mapStringForOutGoingNonces + `,`,
		`}`,
	}, "")
	return s
}
func (this *RoundNum) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&RoundNum{`,
		`Num:` + fmt.Sprintf("%v", this.Num) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringBootstrapData(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *MiniBlocksInMeta) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBootstrapData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MiniBlocksInMeta: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MiniBlocksInMeta: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetaHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBootstrapData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBootstrapData
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBootstrapData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MetaHash = append(m.MetaHash[:0], dAtA[iNdEx:postIndex]...)
			if m.MetaHash == nil {
				m.MetaHash = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MiniBlocksHashes", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBootstrapData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBootstrapData
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBootstrapData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MiniBlocksHashes = append(m.MiniBlocksHashes, make([]byte, postIndex-iNdEx))
			copy(m.MiniBlocksHashes[len(m.MiniBlocksHashes)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType == 0 {
				var v int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowBootstrapData
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.FullyProcessed = append(m.FullyProcessed, bool(v != 0))
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowBootstrapData
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthBootstrapData
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthBootstrapData
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				elementCount = packedLen
				if elementCount != 0 && len(m.FullyProcessed) == 0 {
					m.FullyProcessed = make([]bool, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowBootstrapData
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.FullyProcessed = append(m.FullyProcessed, bool(v != 0))
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field FullyProcessed", wireType)
			}
		case 4:
			if wireType == 0 {
				var v int32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowBootstrapData
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.IndexOfLastTxProcessed = append(m.IndexOfLastTxProcessed, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowBootstrapData
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthBootstrapData
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthBootstrapData
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.IndexOfLastTxProcessed) == 0 {
					m.IndexOfLastTxProcessed = make([]int32, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v int32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowBootstrapData
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= int32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.IndexOfLastTxProcessed = append(m.IndexOfLastTxProcessed, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field IndexOfLastTxProcessed", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBootstrapData(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBootstrapData
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBootstrapData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BootstrapHeaderInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBootstrapData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BootstrapHeaderInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BootstrapHeaderInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShardId", wireType)
			}
			m.ShardId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBootstrapData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ShardId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBootstrapData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBootstrapData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBootstrapData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBootstrapData
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBootstrapData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = append(m.Hash[:0], dAtA[iNdEx:postIndex]...)
			if m.Hash == nil {
				m.Hash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBootstrapData(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBootstrapData
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBootstrapData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PendingMiniBlocksInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBootstrapData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PendingMiniBlocksInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PendingMiniBlocksInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShardID", wireType)
			}
			m.ShardID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBootstrapData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ShardID |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MiniBlocksHashes", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBootstrapData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBootstrapData
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBootstrapData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MiniBlocksHashes = append(m.MiniBlocksHashes, make([]byte, postIndex-iNdEx))
			copy(m.MiniBlocksHashes[len(m.MiniBlocksHashes)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBootstrapData(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBootstrapData
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBootstrapData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BootstrapData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBootstrapData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BootstrapData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BootstrapData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastHeader", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBootstrapData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBootstrapData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBootstrapData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LastHeader.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastCrossNotarizedHeaders", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBootstrapData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBootstrapData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBootstrapData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastCrossNotarizedHeaders = append(m.LastCrossNotarizedHeaders, BootstrapHeaderInfo{})
			if err := m.LastCrossNotarizedHeaders[len(m.LastCrossNotarizedHeaders)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProcessedMiniBlocks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBootstrapData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBootstrapData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBootstrapData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProcessedMiniBlocks = append(m.ProcessedMiniBlocks, MiniBlocksInMeta{})
			if err := m.ProcessedMiniBlocks[len(m.ProcessedMiniBlocks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HighestFinalBlockNonce", wireType)
			}
			m.HighestFinalBlockNonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBootstrapData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HighestFinalBlockNonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastRound", wireType)
			}
			m.LastRound = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBootstrapData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastRound |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastSelfNotarizedHeaders", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBootstrapData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBootstrapData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBootstrapData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastSelfNotarizedHeaders = append(m.LastSelfNotarizedHeaders, BootstrapHeaderInfo{})
			if err := m.LastSelfNotarizedHeaders[len(m.LastSelfNotarizedHeaders)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingMiniBlocks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBootstrapData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBootstrapData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBootstrapData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PendingMiniBlocks = append(m.PendingMiniBlocks, PendingMiniBlocksInfo{})
			if err := m.PendingMiniBlocks[len(m.PendingMiniBlocks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodesCoordinatorConfigKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBootstrapData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBootstrapData
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBootstrapData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodesCoordinatorConfigKey = append(m.NodesCoordinatorConfigKey[:0], dAtA[iNdEx:postIndex]...)
			if m.NodesCoordinatorConfigKey == nil {
				m.NodesCoordinatorConfigKey = []byte{}
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochStartTriggerConfigKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBootstrapData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBootstrapData
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBootstrapData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EpochStartTriggerConfigKey = append(m.EpochStartTriggerConfigKey[:0], dAtA[iNdEx:postIndex]...)
			if m.EpochStartTriggerConfigKey == nil {
				m.EpochStartTriggerConfigKey = []byte{}
			}
			iNdEx = postIndex
		case 20:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutGoingNonces", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBootstrapData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBootstrapData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBootstrapData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.OutGoingNonces == nil {
				m.OutGoingNonces = make(map[string]uint64)
			}
			var mapkey string
			var mapvalue uint64
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowBootstrapData
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowBootstrapData
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthBootstrapData
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthBootstrapData
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowBootstrapData
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipBootstrapData(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthBootstrapData
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.OutGoingNonces[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBootstrapData(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBootstrapData
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBootstrapData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RoundNum) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBootstrapData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RoundNum: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RoundNum: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Num", wireType)
			}
			m.Num = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBootstrapData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Num |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBootstrapData(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBootstrapData
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBootstrapData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBootstrapData(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBootstrapData
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBootstrapData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBootstrapData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBootstrapData
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBootstrapData
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBootstrapData
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBootstrapData        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBootstrapData          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBootstrapData = fmt.Errorf("proto: unexpected end of group")
)
